add enderungen im bestellungs prozess
myroslav111/bestellung-service pull request #6
Opened 2024-11-06 15:10 UTC by myroslav111

2024-11-06 15:24 UTC, ReReRl1 commented on src/main/java/info/bestellungsservice/apothekebestellungservice/apotheke/Apotheke.java
> +                System.out.println("Bitte gben Sie das gewünschte Produkte ein:");
in Zeile 167 "gben" da fehlt ein e. und Produkt zum Singular ändern (Produkt)

2024-11-06 15:25 UTC, ReReRl1 commented on src/main/java/info/bestellungsservice/apothekebestellungservice/apotheke/Apotheke.java
> +                System.out.println("Login erfolgreich");
ein "." oder "!" am Ende des Satzes.

2024-11-06 15:30 UTC, ReReRl1 commented on src/main/java/info/bestellungsservice/apothekebestellungservice/utils/BenutzerAnmeldeDatenAbfragen.java
> +        System.out.println("Email-Adresse");
":" hinzufügen

2024-11-06 15:32 UTC, ReReRl1 requested changes
Mehrere Verbesserungsmöglichkeiten :D

2024-11-06 15:32 UTC, ReReRl1 commented on src/main/java/info/bestellungsservice/apothekebestellungservice/utils/BenutzerAnmeldeDatenAbfragen.java
> -        System.out.println("Geben Sie Ihre Passwort");
":" hinzufügen, damit der User weiß, da muss irgendwas passieren.

2024-11-07 12:16 UTC, Stev3eM requested changes

2024-11-07 12:16 UTC, Stev3eM commented on src/main/java/info/bestellungsservice/apothekebestellungservice/apotheke/Apotheke.java
> +                System.out.println("Wie viele Stück?");
"Wie viel Stück?" -> "Geben Sie die gewünschte Anzahl ein:"

2024-11-07 12:23 UTC, Stev3eM requested changes

2024-11-07 12:23 UTC, Stev3eM commented on src/main/java/info/bestellungsservice/apothekebestellungservice/ProduktList.java
> +            System.out.println(produkt.getMedikamenteName() + "--> " + "Bestellungsnummer______" + produkt.getMedikamenteNummer() );
Wofür ist bei "Bestellnummer______" der lange unterstrich? Und was ist der Unterschied zur MedikamenteNummer?

2024-11-07 12:43 UTC, Stev3eM approved these changes

2024-11-07 13:20 UTC, Stev3eM approved these changes

2024-11-07 13:36 UTC, merged